INSERT INTO ROLE(ID, ROLE) VALUES(1, 'ADMIN');
INSERT INTO ROLE(ID, ROLE) VALUES(2, 'USER');

INSERT INTO USER(ID, USERNAME, PASSWORD, ACTIVE) VALUES(1, 'admin', '$2a$10$nhU38YCtaWpLzTIeG/uAIeGnu7GItrvGsQAQrgsjM9hN19cGp25N6', 1);

INSERT INTO user_role(user_id, role_id) VALUES (1,1);